### ISSUE TITLE
Upgrade github actions to version not giving warnings

### ISSUE THREAD

**Issue by stolsvik** [centiservice/mats3#75]
I currently have a boatload of these warnings from the CI GH Actions runs:
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

These are coming from the included GHA steps in my `gradle.yml` file, i.e. not directly referenced.

However, when finding the example page of how to set up a CI GH Actions run with Java and Gradle, it still refers to exactly the versions I use:
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
-> https://github.com/actions/starter-workflows/blob/main/ci/gradle.yml

```
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
 ```

Thus, when this page changes, change along.
